"""Tool definitions — imported by main_api.py for GET /tools endpoint"""

TOOL_DEFINITIONS = [
    {"type":"function","function":{"name":"search_serp","description":"Google SERP results for a keyword. Returns organic results, PAA, featured snippets.","parameters":{"type":"object","properties":{"query":{"type":"string"},"num_results":{"type":"integer","description":"1-20, default 10"},"country":{"type":"string","description":"us|uk|au|ca etc"}},"required":["query"]}}},
    {"type":"function","function":{"name":"search_web","description":"General web search.","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}},
    {"type":"function","function":{"name":"search_news","description":"Recent news articles for a topic.","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}},
    {"type":"function","function":{"name":"get_related_questions","description":"People Also Ask questions from Google for a keyword.","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}},
    {"type":"function","function":{"name":"get_keyword_volume","description":"Monthly search volume for keywords from DataForSEO.","parameters":{"type":"object","properties":{"keywords":{"type":"array","items":{"type":"string"}},"location_code":{"type":"integer","description":"2840=US, 2826=UK"}},"required":["keywords"]}}},
    {"type":"function","function":{"name":"get_keyword_difficulty","description":"Keyword difficulty score 0-100 + CPC.","parameters":{"type":"object","properties":{"keywords":{"type":"array","items":{"type":"string"}}},"required":["keywords"]}}},
    {"type":"function","function":{"name":"get_keyword_suggestions","description":"Related keyword suggestions for a seed keyword.","parameters":{"type":"object","properties":{"keyword":{"type":"string"},"limit":{"type":"integer"}},"required":["keyword"]}}},
    {"type":"function","function":{"name":"get_competitor_keywords","description":"Keywords a competitor domain ranks for in top 10.","parameters":{"type":"object","properties":{"domain":{"type":"string"},"limit":{"type":"integer"}},"required":["domain"]}}},
    {"type":"function","function":{"name":"gsc_get_rankings","description":"Page rankings, impressions, CTR from Google Search Console.","parameters":{"type":"object","properties":{"site_url":{"type":"string"},"page_url":{"type":"string"},"days":{"type":"integer"}},"required":["site_url"]}}},
    {"type":"function","function":{"name":"gsc_get_top_queries","description":"Top search queries driving clicks from GSC.","parameters":{"type":"object","properties":{"site_url":{"type":"string"},"page_url":{"type":"string"},"days":{"type":"integer"},"limit":{"type":"integer"}},"required":["site_url"]}}},
    {"type":"function","function":{"name":"gsc_detect_ranking_drops","description":"Detect pages with significant ranking drops for content decay monitoring.","parameters":{"type":"object","properties":{"site_url":{"type":"string"},"drop_threshold":{"type":"number"},"days":{"type":"integer"}},"required":["site_url"]}}},
    {"type":"function","function":{"name":"ga4_get_page_traffic","description":"Sessions, users, bounce rate for a page from GA4.","parameters":{"type":"object","properties":{"page_path":{"type":"string"},"days":{"type":"integer"}},"required":["page_path"]}}},
    {"type":"function","function":{"name":"ga4_get_top_pages","description":"Top pages by sessions from GA4.","parameters":{"type":"object","properties":{"days":{"type":"integer"},"limit":{"type":"integer"}},"required":[]}}},
    {"type":"function","function":{"name":"ga4_detect_traffic_drops","description":"Detect pages with significant traffic drops vs previous period.","parameters":{"type":"object","properties":{"days":{"type":"integer"},"drop_pct":{"type":"number"}},"required":[]}}},
]
